- id: aws-ia-meta-hook
  name: Meta hook wrapper
  require_serial: true
  entry: hooks/hook-wrapper.sh
  language: script
  always_run: true
  verbose: true

- id: aws-ia-highpoint-hook
  name: Highpoint hook wrapper
  require_serial: true
  entry: specific/hooks/highpoint-hook-wrapper.sh
  language: script
  always_run: true
  verbose: true
