---

fail_fast: false
minimum_pre_commit_version: "2.6.0"

repos:
  -
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 8fe62d14e0b4d7d845a7022c5c2c3ae41bdd3f26  # frozen: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        exclude: "templates/.*"

  - # see https://github.com/antonbabenko/pre-commit-terraform
    # Temporary, pending approval/merge of https://github.com/antonbabenko/pre-commit-terraform/pull/347
    # repo: https://github.com/antonbabenko/pre-commit-terraform
    # rev: v1.64.0
    repo: https://github.com/aws-ia/pre-commit-terraform
    rev: 76914e65fafa5ccb6e10a43d821b8543507ed234
    hooks:
      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_fmt
      - id: terraform_fmt

      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_validate
      - id: terraform_validate
        exclude: examples/.*

      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_docs
      - id: terraform_docs
        args:
          - "--args=--config=.terraform-docs.yaml"

      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_providers_lock
      - id: terraform_providers_lock

      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_tflint
      - id: terraform_tflint
        exclude: 'examples/.*'
        args:
          - "--args=--config=__GIT_WORKING_DIR__/.tflint.hcl"

      - id: terraform_tfsec
        args:
          - "--args=--exclude-downloaded-modules"
          - "--args=--custom-check-dir=__GIT_WORKING_DIR__/.tfsec"
        files: \.tf$
        exclude: \.terraform\/.*$
  - repo: https://github.com/aws-ia/pre-commit-hooks
    rev: 16be3ef859223383f402c8523bfd3bbb5f750894
    hooks:
      - id: git-submodule-sanity-check
        always_run: true
